baseurl: '/iconic-resume'

name: Toe Aung Ye Yint

headline: >-
  Master of Information Technology degree from Monash University with over 2 years of experience in software development.
  Passionate about artificial intelligence and more.

contact:
  -
    icon: 'bi bi-globe'
    name: toeaung-yeyint.github.io
    url: 'https://toeaung-yeyint.github.io/'  # replace with your own address
  -
    icon: 'bi bi-linkedin'
    name: toeaung-yeyint
    url: 'https://www.linkedin.com/in/toeaung-yeyint'  # replace with your own address
  -
    icon: 'bi bi-envelope'
    name: toeaungyeyint@gmail.com
    url: 'mailto:toeaungyeyint@gmail.com'  # replace with your own email
  -
    icon: 'bi bi-phone'
    name: 0451 540 057
    url: 'tel:+61451540057'  # Replace with your mobile number prefixed with 'tel:'

language:
  - English
  - Burmese

techstack:
  -
    icon: js.png
    name: JavaScript
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: typescript.png
    name: TypeScript
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: react.png
    name: React
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: vue.png
    name: Vue
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: python.png
    name: Python
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: html.png
    name: HTML
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: css.png
    name: CSS
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: scss.png
    name: SCSS
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: tailwind.png
    name: Tailwind
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: figma.png
    name: Figma
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: fastapi.png
    name: AWS
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: firebase.png
    name: Firebase
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: sql.png
    name: sql
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: mongodb.png
    name: MongoDB
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: wordpress.png
    name: WordPress
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: squiz.png
    name: Squiz Matrix
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: vite.png
    name: Vite
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: git.png
    name: git
    link: 'https://github.com/'  # replace with your own repo address

hobby:
  - Available request upon

########### Education
education:
  -
    icon: monash.jpg
    school: Monash University
    degree: Master of Information Technology 
    loc: Melbourne, Australia
    time: Mar 2020 ~ Jul 2022
    description: >-
      GPA: 4.0/4.0
  -
    icon: thanlyin.jpg
    school: Technological University (Thanlyin)
    degree: Bachelor of Technology / Bachelor of Architecture 
    loc: Yangon, Myanmar
    time: 2011 ~ 2018
    description: >-
      GPA: 4.0/4.0
      
########### Experience (optional)
experience:
  -
    icon: deakin.jpg
    company: Deakin University
    role: Digital Services Officer
    loc: Melbourne, Australia
    time: Oct 2023 ~ present
    description: >-
      - Developed a web application to streamline managing digital assets, providing division staff a centralized hub for convenient access and resulting in 80% increase in asset utilisation across the division.
      <br>
      - Revamped existing websites on Squiz Matrix (CMS) and WordPress (CMS) using HTML, CSS, and JavaScript to modernize and optimize UI/UX, resulting in intuitive user interfaces and enhanced user experience.
      <br>
      - Implemented process automation to streamline manual workflows, reducing manual tasks by 50%, minimising human errors and amplifying efficiency across the division.

  -
    icon: monash.jpg
    company: Monash University
    role: Web Developer
    loc: Melbourne, Australia
    time: Aug 2022 ~ Oct 2023
    description: >-
      - Designed and developed responsive websites on Squiz Matrix (CMS) using HTML, CSS, JavaScript with user-centric design principles, increased user engagement by 30% and improved navigation efficiency by 20%.
      <br>
      - Applied innovative problem-solving techniques to address complex web-related issues on Zendesk (help desk software), resulted in enhanced system reliability and improved user satisfaction.
      <br>
      - Conducted comprehensive keyword research using Semrush (keyword research tool) to optimize website content for search engines, resulted in 50% increase in visibility and organic traffic.


########### Publications (optional)
# publication:
#   -
#     title: An Awesome Paper with an Awesome Title 2
#     author: Josh Lee
#     journal: International Conference on Machine Learning (ICML)
#     year: 2022
#     link: 'http://arxiv.org/'
#   -
#     title: An Awesome Paper with an Awesome Title 1
#     author: Josh Lee
#     journal: International Conference on Learning Representations (ICLR)
#     year: 2021
#     link: 'http://arxiv.org/'

########### Projects (optional)
project:
  -
    icon: github.svg
    name: teams-titles
    link: 'https://toeaung-yeyint.github.io/teams-titles/'
    description: |
      Developed a Vue.js app showcasing UEFA Champions League history for top teams, with CRUD functionality.
  -
    icon: github.svg
    name: calculate-shapes-volumes
    link: 'https://toeaung-yeyint.github.io/calculate-shapes-volume/'
    description: |
      Created a Vue.js SPA (single-page application) using Vue Router to calculate volumes of various 3D shapes.
  -
    icon: github.svg
    name: image-object-detection
    link: 'https://toeaung-yeyint.github.io/image-object-detection/'
    description: |
      Implemented ml5.js in a Vue.js app for object detection in images with CocoSsd and YOLO models.
