baseurl: '/iconic-resume'

name: Toe Aung Ye Yint

headline: >-
  Master of Information Technology degree from Monash University with over 2 years of experience in software development.
  Passionate about artificial intelligence and more.

contact:
  -
    icon: 'bi bi-globe'
    name: toeaung-yeyint.github.io
    url: 'https://toeaung-yeyint.github.io/'  # replace with your own address
  -
    icon: 'bi bi-linkedin'
    name: toeaung-yeyint
    url: 'https://www.linkedin.com/in/toeaung-yeyint'  # replace with your own address
  -
    icon: 'bi bi-envelope'
    name: toeaungyeyint@gmail.com
    url: 'mailto:toeaungyeyint@gmail.com'  # replace with your own email
  -
    icon: 'bi bi-phone'
    name: 0451 540 057
    url: 'tel:+61451540057'  # Replace with your mobile number prefixed with 'tel:'

language:
  - English
  - Burmese

techstack:
  -
    icon: python.png
    name: Python
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: pytorch.png
    name: PyTorch
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: pyspark.png
    name: PySpark
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: fastapi.png
    name: FastAPI
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: js.png
    name: JavaScript
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: svelte.png
    name: Svelte
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: react.png
    name: React
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: nextjs.svg
    name: Next.js
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: vite.png
    name: Vite
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: swift.png
    name: Swift
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: cpp.png
    name: C++
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: sql.png
    name: sql
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: git.png
    name: git
    link: 'https://github.com/'  # replace with your own repo address

hobby:
  - Available request upon

########### Education
education:
  -
    icon: monash.jpg
    school: Monash University
    degree: Master of Information Technology 
    loc: Boston, MA
    time: March 2020 ~ July 2022
    description: >-
      GPA: 4.0/4.0
  -
    icon: thanlyin.jpg
    school: Technological University (Thanlyin)
    degree: Bachelor of Technology / Bachelor of Architecture 
    loc: Pittsburgh, PA
    time: 2011 ~ 2018
    description: >-
      GPA: 4.0/4.0
      
########### Experience (optional)
experience:
  -
    icon: deakin.jpg
    company: Deakin University
    role: Digital Services Officer
    loc: Mountain View, CA
    time: October 2023 ~ present
    description: >-
      - Developed a web application to streamline managing digital assets, providing division staff a centralized hub for convenient access and resulting in 80% increase in asset utilisation across the division.
      <br>
      - Revamped existing websites on Squiz Matrix (CMS) and WordPress (CMS) using HTML, CSS, and JavaScript to modernize and optimize UI/UX, resulting in intuitive user interfaces and enhanced user experience.
      <br>
      - Implemented process automation to streamline manual workflows, reducing manual tasks by 50%, minimising human errors and amplifying efficiency across the division.

  -
    icon: monash.jpg
    company: Monash University
    role: Web Developer
    loc: Seattle, WA
    time: August 2022 ~ October 2023
    description: >-
      - Designed and developed responsive websites on Squiz Matrix (CMS) using HTML, CSS, JavaScript with user-centric design principles, increased user engagement by 30% and improved navigation efficiency by 20%.
      <br>
      - Applied innovative problem-solving techniques to address complex web-related issues on Zendesk (help desk software), resulted in enhanced system reliability and improved user satisfaction.
      <br>
      - Conducted comprehensive keyword research using Semrush (keyword research tool) to optimize website content for search engines, resulted in 50% increase in visibility and organic traffic.


########### Publications (optional)
# publication:
#   -
#     title: An Awesome Paper with an Awesome Title 2
#     author: Josh Lee
#     journal: International Conference on Machine Learning (ICML)
#     year: 2022
#     link: 'http://arxiv.org/'
#   -
#     title: An Awesome Paper with an Awesome Title 1
#     author: Josh Lee
#     journal: International Conference on Learning Representations (ICLR)
#     year: 2021
#     link: 'http://arxiv.org/'

########### Projects (optional)
project:
  -
    icon: github.svg
    name: TEAMS-TITLES
    link: 'https://toeaung-yeyint.github.io/teams-titles/'
    description: |
      This fully-fledged Vue app allows users to view the winning history of top European football teams in the UEFA Champions League such as Real Madrid, Barcelona, Manchester United, etc. Additionally, the app provides functionality for users to add new teams, update or remove existing ones.
  -
    icon: github.svg
    name: CALCULATE-SHAPES-VOLUMES
    link: 'https://toeaung-yeyint.github.io/calculate-shapes-volume/'
    description: |
      This fully-fledged Vue app utilizes Vue Router to create a single-page application (SPA) with multiple views. It enables users to calculate the volume of various 3D shapes, giving them the flexibility to choose their preferred unit of measure.
  -
    icon: github.svg
    name: IMAGE-OBJECT-DETECTION
    link: 'https://toeaung-yeyint.github.io/image-object-detection/'
    description: |
      This fully-fledged Vue app utilizes the power of ml5.js, a machine learning JavaScript library, to enable users to identify objects in images. Notably, users have the flexibility to choose from various object detection models such as CocoSsd or YOLO. Additionally, the app shows the number of detected objects along with their corresponding labels, and confidence scores.
